# Generated by Django 5.1.7 on 2025-03-20 12:18

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('studio', 'Studio'), ('hotel', 'Hotel'), ('hostel', 'Hostel')], max_length=50)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'WiFi'), ('ac', 'Air Conditioning'), ('heating', 'Heating'), ('kitchen', 'Kitchen'), ('parking', 'Parking'), ('washer', 'Washer'), ('dryer', 'Dryer'), ('tv', 'TV'), ('pool', 'Pool'), ('gym', 'Gym'), ('breakfast', 'Breakfast Included'), ('pets', 'Pets Allowed'), ('smoking', 'Smoking Allowed'), ('elevator', 'Elevator'), ('wheelchair', 'Wheelchair Accessible'), ('hottub', 'Hot Tub'), ('sauna', 'Sauna'), ('bbq', 'BBQ Grill'), ('fireplace', 'Fireplace'), ('balcony', 'Balcony'), ('garden', 'Garden'), ('private_entrance', 'Private Entrance'), ('cable_tv', 'Cable TV'), ('coffee_maker', 'Coffee Maker'), ('iron', 'Iron'), ('hair_dryer', 'Hair Dryer'), ('luggage_drop', 'Luggage Drop Off'), ('essentials', 'Essentials (towels, bed sheets, soap, and toilet paper)'), ('workspace', 'Laptop Friendly Workspace'), ('self_check_in', 'Self Check-in'), ('family_friendly', 'Family/Kid Friendly')], max_length=500, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='property_cover_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.property')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.profile')),
            ],
        ),
    ]
