# Generated by Django 5.1.7 on 2025-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_review_comment_alter_review_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='cover_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
