# Generated by Django 5.1.7 on 2025-03-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_property_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='host',
        ),
    ]
