# Generated by Django 5.1.7 on 2025-03-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_property_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
