# Generated by Django 5.1.7 on 2025-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_property_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='cover_images/'),
        ),
    ]
