# Generated by Django 5.1.7 on 2025-03-26 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_id'),
        ('listings', '0011_alter_property_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.profile'),
        ),
    ]
