# Generated by Django 5.1.7 on 2025-03-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_id'),
        ('listings', '0012_property_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.profile'),
        ),
    ]
