# Generated by Django 5.1.7 on 2025-03-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_property_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
